version: "3"

services:
  gitserver:
    container_name: ${GITSERVER_CONTAINER_NAME:-gitserver}
    image: sanrep/gitserver
    # build: .
    restart: unless-stopped

    # Write logging to stderr during setup for debugging, comment afterwards
    # command: ["/usr/sbin/sshd", "-D", "-e"]

    volumes:
      # Directory with git repositories
      - ${GIT_REPOSITORIES_DIR}:/srv/git

      # File containing the SSH keys of clients that will be allowed
      # to use this service through a public key
      - ${AUTHORIZED_KEYS_FILE}:/home/git/.ssh/authorized_keys

      # Directory with host SSH keys to use instead of the default ones
      - ${SSH_HOST_KEYS_DIR}:${SSH_HOST_KEYS_PATH}:ro

      # Custom configuration file for the OpenSSH daemon
      - ${SSHD_CONFIG_FILE:-./sshd_config}:/etc/ssh/sshd_config:ro

      # File containing the password for the git user
      # - ${PASSWORD_FILE}:/run/secrets/git_password:ro

    ports:
      - "${GITSERVER_PORT:-2222}:22"

    env_file:
      - .env

# Use Docker secrets to provide the git password file instead of mounting
#     secrets:
#       - git_password
#
# secrets:
#   git_password:
#     file: ${GIT_PASSWORD_FILE}
