#!/bin/sh

if [ -z "$1" ]
  then
	echo "Please provide a name for the repository."
else
	REPO_NAME=`echo $1 | sed 's/\(.*\)\(\.git$\)/\1/g'`.git
	echo "Creating repository $REPO_NAME"
	git init --bare --initial-branch=main git/$REPO_NAME
fi
